//---THIS-FILE-WAS-PATCHED , org=D:\projects\cef_binary_3.3071.1647.win32\cpptoc\navigation_entry_visitor_cpptoc.cc
// Copyright (c) 2017 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=06ab08bb628eb7ec388604c9b393e9e9e1200435$
//

#include "libcef_dll/cpptoc/navigation_entry_visitor_cpptoc.h"
#include "libcef_dll/ctocpp/navigation_entry_ctocpp.h"

//---kneadium-ext-begin
#include "../myext/ExportFuncAuto.h"
#include "../myext/InternalHeaderForExportFunc.h"
//---kneadium-ext-end

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

int CEF_CALLBACK
navigation_entry_visitor_visit(struct _cef_navigation_entry_visitor_t* self,
                               struct _cef_navigation_entry_t* entry,
                               int current,
                               int index,
                               int total) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return 0;
  // Verify param: entry; type: refptr_diff
  DCHECK(entry);
  if (!entry)
    return 0;

//---kneadium-ext-begin
#if ENABLE_KNEADIUM_EXT
auto me = CefNavigationEntryVisitorCppToC::Get(self);
const int CALLER_CODE=(CefNavigationEntryVisitorExt::_typeName << 16) | CefNavigationEntryVisitorExt::CefNavigationEntryVisitorExt_Visit_1;
auto m_callback= me->GetManagedCallBack(CALLER_CODE);
if(m_callback){
CefNavigationEntryVisitorExt::VisitArgs args1(entry,current,index,total);
m_callback(CALLER_CODE, &args1.arg);
 if (((args1.arg.myext_flags >> 21) & 1) == 1){
 return args1.arg.myext_ret_value;
}
}
#endif
//---kneadium-ext-end

  // Execute
  bool _retval = CefNavigationEntryVisitorCppToC::Get(self)->Visit(
      CefNavigationEntryCToCpp::Wrap(entry), current ? true : false, index,
      total);

  // Return type: bool
  return _retval;
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefNavigationEntryVisitorCppToC::CefNavigationEntryVisitorCppToC() {
  GetStruct()->visit = navigation_entry_visitor_visit;
}

template <>
CefRefPtr<CefNavigationEntryVisitor>
CefCppToCRefCounted<CefNavigationEntryVisitorCppToC,
                    CefNavigationEntryVisitor,
                    cef_navigation_entry_visitor_t>::
    UnwrapDerived(CefWrapperType type, cef_navigation_entry_visitor_t* s) {
  NOTREACHED() << "Unexpected class type: " << type;
  return NULL;
}

#if DCHECK_IS_ON()
template <>
base::AtomicRefCount
    CefCppToCRefCounted<CefNavigationEntryVisitorCppToC,
                        CefNavigationEntryVisitor,
                        cef_navigation_entry_visitor_t>::DebugObjCt = 0;
#endif

template <>
CefWrapperType
    CefCppToCRefCounted<CefNavigationEntryVisitorCppToC,
                        CefNavigationEntryVisitor,
                        cef_navigation_entry_visitor_t>::kWrapperType =
        WT_NAVIGATION_ENTRY_VISITOR;
