//---THIS-FILE-WAS-PATCHED , org=D:\projects\cef_binary_3.3071.1647.win32\cpptoc\read_handler_cpptoc.cc
// Copyright (c) 2017 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=f92e2d8dea0ebbb5d0e2bd31cd7e8322db6e95fc$
//

#include "libcef_dll/cpptoc/read_handler_cpptoc.h"

//---kneadium-ext-begin
#include "../myext/ExportFuncAuto.h"
#include "../myext/InternalHeaderForExportFunc.h"
//---kneadium-ext-end

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

size_t CEF_CALLBACK read_handler_read(struct _cef_read_handler_t* self,
                                      void* ptr,
                                      size_t size,
                                      size_t n) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return 0;
  // Verify param: ptr; type: simple_byaddr
  DCHECK(ptr);
  if (!ptr)
    return 0;

//---kneadium-ext-begin90
#if ENABLE_KNEADIUM_EXT
auto me = CefReadHandlerCppToC::Get(self);
const int CALLER_CODE=(CefReadHandlerExt::_typeName << 16) | CefReadHandlerExt::CefReadHandlerExt_Read_1;
auto m_callback= me->GetManagedCallBack(CALLER_CODE);
if(m_callback){
CefReadHandlerExt::ReadArgs args1(ptr,size,n);
m_callback(CALLER_CODE, &args1.arg);
 if (((args1.arg.myext_flags >> 21) & 1) == 1){
 return args1.arg.myext_ret_value;
}
}
#endif
//---kneadium-ext-end

  // Execute
  size_t _retval = CefReadHandlerCppToC::Get(self)->Read(ptr, size, n);

  // Return type: simple
  return _retval;
}

int CEF_CALLBACK read_handler_seek(struct _cef_read_handler_t* self,
                                   int64 offset,
                                   int whence) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return 0;

//---kneadium-ext-begin89
#if ENABLE_KNEADIUM_EXT
auto me = CefReadHandlerCppToC::Get(self);
const int CALLER_CODE=(CefReadHandlerExt::_typeName << 16) | CefReadHandlerExt::CefReadHandlerExt_Seek_2;
auto m_callback= me->GetManagedCallBack(CALLER_CODE);
if(m_callback){
CefReadHandlerExt::SeekArgs args1(offset,whence);
m_callback(CALLER_CODE, &args1.arg);
 if (((args1.arg.myext_flags >> 21) & 1) == 1){
 return args1.arg.myext_ret_value;
}
}
#endif
//---kneadium-ext-end

  // Execute
  int _retval = CefReadHandlerCppToC::Get(self)->Seek(offset, whence);

  // Return type: simple
  return _retval;
}

int64 CEF_CALLBACK read_handler_tell(struct _cef_read_handler_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return 0;

//---kneadium-ext-begin88
#if ENABLE_KNEADIUM_EXT
auto me = CefReadHandlerCppToC::Get(self);
const int CALLER_CODE=(CefReadHandlerExt::_typeName << 16) | CefReadHandlerExt::CefReadHandlerExt_Tell_3;
auto m_callback= me->GetManagedCallBack(CALLER_CODE);
if(m_callback){
CefReadHandlerExt::TellArgs args1;
m_callback(CALLER_CODE, &args1.arg);
 if (((args1.arg.myext_flags >> 21) & 1) == 1){
 return args1.arg.myext_ret_value;
}
}
#endif
//---kneadium-ext-end

  // Execute
  int64 _retval = CefReadHandlerCppToC::Get(self)->Tell();

  // Return type: simple
  return _retval;
}

int CEF_CALLBACK read_handler_eof(struct _cef_read_handler_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return 0;

//---kneadium-ext-begin87
#if ENABLE_KNEADIUM_EXT
auto me = CefReadHandlerCppToC::Get(self);
const int CALLER_CODE=(CefReadHandlerExt::_typeName << 16) | CefReadHandlerExt::CefReadHandlerExt_Eof_4;
auto m_callback= me->GetManagedCallBack(CALLER_CODE);
if(m_callback){
CefReadHandlerExt::EofArgs args1;
m_callback(CALLER_CODE, &args1.arg);
 if (((args1.arg.myext_flags >> 21) & 1) == 1){
 return args1.arg.myext_ret_value;
}
}
#endif
//---kneadium-ext-end

  // Execute
  int _retval = CefReadHandlerCppToC::Get(self)->Eof();

  // Return type: simple
  return _retval;
}

int CEF_CALLBACK read_handler_may_block(struct _cef_read_handler_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return 0;

//---kneadium-ext-begin86
#if ENABLE_KNEADIUM_EXT
auto me = CefReadHandlerCppToC::Get(self);
const int CALLER_CODE=(CefReadHandlerExt::_typeName << 16) | CefReadHandlerExt::CefReadHandlerExt_MayBlock_5;
auto m_callback= me->GetManagedCallBack(CALLER_CODE);
if(m_callback){
CefReadHandlerExt::MayBlockArgs args1;
m_callback(CALLER_CODE, &args1.arg);
 if (((args1.arg.myext_flags >> 21) & 1) == 1){
 return args1.arg.myext_ret_value;
}
}
#endif
//---kneadium-ext-end

  // Execute
  bool _retval = CefReadHandlerCppToC::Get(self)->MayBlock();

  // Return type: bool
  return _retval;
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefReadHandlerCppToC::CefReadHandlerCppToC() {
  GetStruct()->read = read_handler_read;
  GetStruct()->seek = read_handler_seek;
  GetStruct()->tell = read_handler_tell;
  GetStruct()->eof = read_handler_eof;
  GetStruct()->may_block = read_handler_may_block;
}

template <>
CefRefPtr<CefReadHandler>
CefCppToCRefCounted<CefReadHandlerCppToC, CefReadHandler, cef_read_handler_t>::
    UnwrapDerived(CefWrapperType type, cef_read_handler_t* s) {
  NOTREACHED() << "Unexpected class type: " << type;
  return NULL;
}

#if DCHECK_IS_ON()
template <>
base::AtomicRefCount CefCppToCRefCounted<CefReadHandlerCppToC,
                                         CefReadHandler,
                                         cef_read_handler_t>::DebugObjCt = 0;
#endif

template <>
CefWrapperType CefCppToCRefCounted<CefReadHandlerCppToC,
                                   CefReadHandler,
                                   cef_read_handler_t>::kWrapperType =
    WT_READ_HANDLER;
