//---THIS-FILE-WAS-PATCHED , org=D:\projects\cef_binary_3.3071.1647.win32\cpptoc\task_cpptoc.cc
// Copyright (c) 2017 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=208bb3fedcf86b782a03fd64c527abcf05f7b297$
//

#include "libcef_dll/cpptoc/task_cpptoc.h"

//---kneadium-ext-begin
#include "../myext/ExportFuncAuto.h"
#include "../myext/InternalHeaderForExportFunc.h"
//---kneadium-ext-end

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK task_execute(struct _cef_task_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return;

//---kneadium-ext-begin1
#if ENABLE_KNEADIUM_EXT
auto me = CefTaskCppToC::Get(self);
const int CALLER_CODE=(CefTaskExt::_typeName << 16) | CefTaskExt::CefTaskExt_Execute_1;
auto m_callback= me->GetManagedCallBack(CALLER_CODE);
if(m_callback){
CefTaskExt::ExecuteArgs args1;
m_callback(CALLER_CODE, &args1.arg);
 if (((args1.arg.myext_flags >> 21) & 1) == 1){
return;
}
}
#endif
//---kneadium-ext-end

  // Execute
  CefTaskCppToC::Get(self)->Execute();
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefTaskCppToC::CefTaskCppToC() {
  GetStruct()->execute = task_execute;
}

template <>
CefRefPtr<CefTask>
CefCppToCRefCounted<CefTaskCppToC, CefTask, cef_task_t>::UnwrapDerived(
    CefWrapperType type,
    cef_task_t* s) {
  NOTREACHED() << "Unexpected class type: " << type;
  return NULL;
}

#if DCHECK_IS_ON()
template <>
base::AtomicRefCount
    CefCppToCRefCounted<CefTaskCppToC, CefTask, cef_task_t>::DebugObjCt = 0;
#endif

template <>
CefWrapperType
    CefCppToCRefCounted<CefTaskCppToC, CefTask, cef_task_t>::kWrapperType =
        WT_TASK;
